### ISSUE TITLE
obuild doesn't compile with ocaml-5

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-obuild/obuild#186] opened 2023-01-11 02:57 UTC
I don't need it, this is just FYI.

**Comment by reubenrowe** [comment] 2023-10-29 11:06
It looks like the latest commit 5845999 fixes this? Will a new version of obuild with this fix be published to OPAM, please?

I have a project relying on the opam published version of Jean-Christophe Filliâtre's hashset package, which uses obuild to compile. So it would be preferable to have the published obuild package building with OCaml >= 5.x

Thanks!

**Comment by UnixJunkie** [comment] 2023-10-30 00:18
Maybe, you could also pass hashset to dune and be safe for the long term.

**Comment by jeromemaloberti** [comment] 2023-10-30 22:11
I can create a new version easily, but I don't know how to update the opam package. I need to check that.

**Comment by reubenrowe** [comment] 2023-10-31 11:28
@UnixJunkie yes, I will submit a pull request for porting hashset to dune.
@jeromemaloberti I think it would still be good to have the OPAM version of obuild up to date.

**Comment by jeromemaloberti** [comment] 2023-10-31 12:39
I never updated it, so it is new. But I'm confused because:
- I don't think I can use opam publish, since I have to remove the constraint on the compiler version, and I don't see how I can do that.
- when I try to do "opam install ." in my update directory, it stubbornly tries to install 0.1.10, instead of 0.1.11. And I don't understand why ...

**Comment by jeromemaloberti** [comment] 2023-10-31 12:57
https://github.com/ocaml/opam-repository/pull/24722
Wait and see.

**Comment by reubenrowe** [comment] 2023-10-31 12:59
You updated as I was writing this ... but for reference:

The problem might be because the `opam` file is specifying opam version 1.2, and `opam-publish` [states](https://github.com/ocaml-opam/opam-publish#prerequisites) that you need to be using OPAM version >=2.0.

You may also need to extend the `opam` file (e.g. adding the package version number there).

**Comment by jeromemaloberti** [comment] 2023-10-31 13:07
I updated the opam file https://github.com/ocaml-obuild/obuild/blob/master/opam
But I forgot to commit it.
I didn't put the package version number, though.

**Comment by jeromemaloberti** [comment] 2023-10-31 13:11
I added the package version and the project name. But I had to commit it before opam decided to compile and install it.
So, it seems to only consider files in git ??

**Comment by reubenrowe** [comment] 2023-10-31 13:37
Yes, well OPAM pulls the code from the repository you specify, so if the changes are not there then they are not visible.

You need to check the results of the CI tests.

- Some linting errors in the `opam` file:
    - You need to add a license field
    - The synopsis field needs to start with an uppercase letter
- The compile seems to be failing for versions 5.0.0 and 5.1.1 - the message is: missing dependency 'unix'

**Comment by jeromemaloberti** [comment] 2023-10-31 13:56
I fixed them and pushed to opam-repo.

**Comment by jeromemaloberti** [comment] 2023-10-31 14:00
Lint complained about "version" and "project", but not on my computer.

**Comment by jeromemaloberti** [comment] 2023-10-31 14:05
If I put unix in depends, it fails to compile on 4.x ...
I guess I need to put a condition ...
But which one ?

**Comment by jeromemaloberti** [comment] 2023-10-31 14:38
@reubenrowe I'm stuck, if I put "unix" in depends, 4.x skips the build because it is unknown. But if I put "base-unix", 5.x complains that unix is missing.

**Comment by reubenrowe** [comment] 2023-10-31 14:46
@jeromemaloberti OK, I will spend some time later today trying to figure this out on my own local copy of obuild

**Comment by jeromemaloberti** [comment] 2023-10-31 15:11
Thank you. I added 
depopts: ["unix" {"ocaml" >= "5.0.0"}]
which seems to help a bit, but some platform (arm, ppc and bsd ?) are still failing ...

**Comment by reubenrowe** [comment] 2023-10-31 19:02
OK, so I think the problem might be that `obuild` actually depends on `ocamfind` to build itself, and this isn't reflected in the `opam` file. I guess some of the test environments used in the CI pipeline must have `ocamlfind` installed by default, while others don't; and it is the ones that don't have it pre-installed that are failing.

You don't need any `depopts: [...]` in the `opam` file, but you do need `depends: [ "ocaml" "ocamlfind" {build} ]`.

**Comment by jeromemaloberti** [comment] 2023-10-31 22:25
obuild doesn't need ocamlfind, but it needs the META files. 
It is also possible that the resolution of dependencies changed between 4 and 5, and the option "+unix" is resolved differently now.
I pushed a change, and waiting for the result.

**Comment by reubenrowe** [comment] 2023-11-01 11:03
It _does_ depend on ocamlfind! At least in the sense that it tries to use it.

https://github.com/ocaml-obuild/obuild/blob/master/obuild/findlibConf.ml#L37

This is ultimately the cause of the build going wrong for OCaml versions 5.x.

The failure is after the `obuild.bootstrap` executable has been built by the `bootstrap` script (which succeeds), and it then tries to run it with the `configure` command.

https://github.com/ocaml-obuild/obuild/blob/master/bootstrap#L103

This reads the `obuild.obuild` configuration file, which lists the `unix` library as a dependency in several places. Part of the configuration is to find the location of this library. 

Before OCaml 5.x, the `unix.cm*` files were in the root directory of the standard library path, and so the library was picked up automatically (by the `Analyze.initializeSystemStdlib` function) and stored in the `Metacache.pkgs_cache` hashtable.

From OCaml 5.1, the location of this library has been moved to a subdirectory, and so it is not added to the packages cache automatically. Then, `ocambuild` falls back on trying to call `ocamlfind` to look up the location of the library. Thus, without `ocamlfind`, the tool will fail to find the library.

So, one solution is to add `ocamlfind` as dependency. We can see now that this has now solved the problems in the OPAM CI pipeline.

Another solution is to modify `Analyze.initializeSystemStdlib` function so that it recurses into subdirectories looking for libraries.

**Comment by jeromemaloberti** [comment] 2023-11-02 23:06
Thank you. That's clear now.
It has been merged, so I will close the issue.
Thank you very much for your help with opam.

**Closed by jeromemaloberti** 2023-11-02 23:06 UTC
