### ISSUE TITLE
does obuild support module aliases feature?

### ISSUE THREAD

**Issue by bobzhang** [ocaml-obuild/obuild#139] opened 2015-06-14 12:44 UTC

**Comment by jordwalke** [comment] 2015-06-15 03:26
I've created an issue to use module aliases for namespacing which should make compile times faster in theory.
https://github.com/ocaml-obuild/obuild/issues/131

**Comment by UnixJunkie** [comment] 2018-04-04 08:37
closing because duplicate of #131

**Closed by UnixJunkie** 2018-04-04 08:37 UTC
